language: generic
sudo: required

services:
  - docker

before_install :
  - docker build -t manojmittal979/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  manojmittal979/react-test npm run test -- --coverage

after_success:
  - docker build -t manojmittal1979/multi-docker-client ./client
  - docker build -t manojmittal1979/multi-docker-nginx ./nginx
  - docker build -t manojmittal1979/multi-docker-server ./server
  - docker build -t manojmittal1979/multi-docker-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push manojmittal1979/multi-docker-client
  - docker push manojmittal1979/multi-docker-nginx
  - docker push manojmittal1979/multi-docker-server
  - docker push manojmittal1979/multi-docker-worker